server:
  port: 8000

spring:
  application:
    name: gateway

  config:
    import: "optional:consul:"

  cloud:
    consul:
      enabled: true
      discovery:
        query-passing: true
      config:
        data-key: application.yml
        prefix: config
        format: yaml
        default-context: defaults
    gateway:
      routes:
        - id: product
          uri: lb://product
          predicates:
            - Path=/product/**

        - id: shopCart
          uri: lb://shopCart
          predicates:
            - Path=/cart/**

        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**

        - id: recommendation
          uri: lb://recommendation
          predicates:
            - Path=/recommendation/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:1234"
            allowed-headers:
              - "*"
            allowed-methods:
              - "GET"
              - "POST"
              - "OPTIONS"
            allow-credentials: true

      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET, POST

logging:
  level:
    org.springframework.cloud.gateway: DEBUG